;PROGRAMA PARA SUMAR EN BINARIO 2, 3 , 1 RESULTADO GUARDADO EN 0X0D
  
    LIST P=16F84
    SUMA1 EQU 0X0C
    RESUL EQU 0X0D
 
    ORG 0
    
    MOVLW b'0010'  ; PONEMOS 2 EN W
    MOVWF SUMA1 ; PASAMOS W A SUMA 1
    MOVLW b'0011' ;PONEMOS 3 EN W
    ADDWF SUMA1,1 ;SUMAMOS W COM SUMA 1 Y RESULTADO EN W
    ;HASTA ESTE PUNTO YA TENEMOS LA SUMA DE 2 NUEMROS
    MOVLW b'0001' ; W->0001
    ADDWF SUMA1,0 ;SUMAMOS W+SUMA1=5 Y EL RESULTADO EN 2
    MOVWF RESUL; PASAMOS W->F RESUL=6
    END