;4.3.1 Realizar una rotación 4 veces hacia la derecha de un 
;registro de valor '10110000'

LIST P = 16F84

VAL1 EQU 0X0B
COUNT EQU 0X0C

ORG 0

;INICIO
INICIO

MOVLW B'10110000';MOVEMOS EL BINARIO A W
MOVWF VAL1;MOVEMOS W A VAL1
MOVLW D'4';MOVEMOS 4 A W
MOVWF COUNT;MOVEMOS W A COUNT
	
LOOP
RRF VAL1,1;ROTACION A LA DERECHA Y GUARDAMOS EN VAL1
DECFSZ COUNT,1;DECREMENTA COUNT Y LO GUARDA DONDE MISMO. SI COUN=0 SALTA INSTRUCCION, SINO SE EJECUTA NORMAL
GOTO LOOP;NOS MANDA AL LOOP
 
;RESULTADO 00001011=11

END