;CONTADOR INFINITO
  LIST P=16F84
#include "p16f84a.inc" ;Incluye las librerias 
  ORG 0
  CONTA EQU H'A0'
  
  BSF STATUS,RP0;BANCO1
  MOVLW B'00000000'
  MOVWF PORTB;PORTB COMO SALIDA
  BCF STATUS,RP0;BANCO1
  
  INICIO
  MOVLW B'00000000';PONEMOS A CERO CONTA
  MOVWF CONTA;REGISTRO CONTADOR
  MOVWF PORTB
  
  ;inicia contador
  CONTAR
  INCFSZ CONTA,1;SI ES IGUAL A 0 POR DESBORDAMIENTO, SALTA UNA INSTRUCCION
  GOTO CONTAR
  MOVLW B'11111111';SI ES CERO POR DESBORAMIENTO
  MOVWF PORTB
  GOTO INICIO
  END
  
  
 
  
  
  