;****************************************************************
;EJEMPLO 1: SUMA 05 Y 02
;***************************************************************
LIST P = 16f84 ;Modelo de pic

SUMA1 EQU 0X0C ;DIRECCION HEXADECIMAL DEL OPERANDO 1
SUMA2 EQU 0X0D ;DIRECCION HEXADECIMAL DEL OPERANDO 2
RESUL EQU 0X0E ;DIRECCION DEL RESULTADO

;**********************************************
ORG 0
;---------------------------------------
;ORIGEN DE LAS INSTRUCCIONES EN EL PROGRAM MEMORY MAP
;DIRECTIVA DE COMPILACION
;****************************************
MOVLW 0X05 ;PONEMOS 05 EN HEXADESIMAL EN W
MOVWF SUMA1 ;PASAMOS W A LA MEMORIA SUMA1
MOVLW 0X02 ;PASAMOS 02 EN HEXADECIMAL EN W
MOVWF SUMA2 ;PASAMOS W A LA MEMORIA SUMA2
MOVFW SUMA1 ;PONEMOS EN W SUMA1 =05
ADDWF SUMA2,0 ;SUMAMOS W+SUMA2 Y EL RESULTADO EN W
MOVWF RESUL ;PONEMOS VALOR ACUMULADOR EN RESUL=7

END ;FIN DE PROGRAMA