;;**************** WELS THEORY ******************
;Descripci?n: Control de 2 Motores DC con el L293D
;Los motores pueden avanzar, retroceder, girar a la izquierda, derecha
;o detenerse.
; 
; Autor:           Wels (@soywels) 
; 
; Copyright: 	   Wels Theory 2018
;
; Fecha	           28 de Febrero del 2018
;  
; Facebook:        https://www.facebook.com/welstheory
; 
; Youtube:         https://www.youtube.com/wels_theory
; 
; Instagram:       https://www.instagram.com/wels_theory/  
;
; CONFIG
; __config 0xFFF1
__CONFIG _FOSC_XT & _WDTE_OFF & _PWRTE_ON & _CP_OFF
LIST P=16F84A
INCLUDE <P16F84A.INC>
	;SERVO
CBLOCK 0X0C
ENDC
	;FIN SERVO
	
;STOP
#DEFINE STOP PORTA,3	
;Motor 1
#DEFINE MOTOR1 PORTA,0
;Motor 2
#DEFINE MOTOR2 PORTA,1
;
;
;SI STOP = 1 -> MODULOS HABILITADOS
; MOTOR1 - MOTOR2 = SALIDA
;   0    -   0    = RETROCESO
;   0    -   1    = IZQUIERDA
;   1    -   0    = DERECHA
;   1    -   1    = ADELANTE
;
;SI STOP = 0 -> MODULOS DESHABILITADOS
;
;
;RB0 = Enable 1 -> RB2 y RB3 controlan el giro Motor1
;RB7 = Enable 2 -> RB4 y RB5 controlan el giro Motor2
;
; ZONA DE C?DIGOS ********************************************************************
	ORG 	0
INICIO
	BSF	STATUS,RP0
	BSF	STOP	    ;ENTRADA
	BSF	MOTOR1
	BSF	MOTOR2
	;SERVO
	BSF	TRISA,2
	BSF	TRISA,4
	
    ;TIMER 0 ASIGNACION DE PRESCALER DE 64
	MOVLW	B'00000101'
	MOVWF	OPTION_REG
	;FIN SERVO
	CLRF	PORTB	    ;SALIDA
	BCF	STATUS,RP0
START
	BTFSS	STOP	    ;STOP = 1?
	GOTO	DETENER	    ;STOP = 0
	BTFSC	MOTOR1	    ;MOTOR1 = 0?
	GOTO	DIRECCION   ;MOTOR1 = 1
	BTFSC	MOTOR2	    ;MOTOR2 = 0?
	GOTO	IZQUIERDA   ;MOTOR1 = 0 - MOTOR2 = 1
	GOTO	ATRAS	    ;MOTOR1 = 0 - MOTOR2 = 0
	;SERVO
	
;**** TIEMPOS **
;** 0.5 MS

TIME_500US	EQU	D'248'

TIMEOF_500US	MOVLW	TIME_500US
				MOVWF	TMR0
				BCF		INTCON,T0IF
TIME_REB		BTFSS	INTCON,T0IF;DETECTA SI SE DESBORDO EL TEMPORIZADOR
				GOTO	TIME_REB
				RETURN

;*** 1MS ****

TIME_1MS	EQU	D'240'

TIMEOF_1MS		MOVLW	TIME_1MS
				MOVWF	TMR0
				BCF		INTCON,T0IF
TIME_REB2		BTFSS	INTCON,T0IF
				GOTO	TIME_REB2
				RETURN

;*** 2MS ****

TIME_2MS	EQU	D'225'

TIMEOF_2MS	MOVLW	TIME_2MS
			MOVWF	TMR0
			BCF		INTCON,T0IF
TIME_REB3	BTFSS	INTCON,T0IF
			GOTO	TIME_REB3
			RETURN

;*** 4MS ****

TIME_4MS	EQU	D'193'

TIMEOF_4MS	MOVLW	TIME_4MS
			MOVWF	TMR0
			BCF		INTCON,T0IF
TIME_REB4	BTFSS	INTCON,T0IF
			GOTO	TIME_REB4
			RETURN

; *** 15 MS ****

TIME_15MS	EQU D'21'

TIMEOF_15MS	MOVLW	TIME_15MS
			MOVWF	TMR0
			BCF		INTCON,T0IF
TIME_REB5	BTFSS	INTCON,T0IF
			GOTO	TIME_REB5
			RETURN

;*** 16 MS ***

TIME_16MS	EQU	D'6'

TIMEOF_16MS	MOVLW	TIME_16MS
			MOVWF	TMR0
			BCF		INTCON,T0IF
TIME_REB6	BTFSS	INTCON,T0IF
			GOTO	TIME_REB6
			RETURN

			;FIN SERVO
	
	
IZQUIERDA
	MOVLW	B'10010001'
	GOTO	SALIDA
DERECHA
	MOVLW	B'10001001'
	GOTO	SALIDA

ATRAS
	MOVLW	B'10100101'
	GOTO	SALIDA
	
DETENER
	CLRW		    ;W = 0
	GOTO	SALIDA
	
DIRECCION
	BTFSS	MOTOR2	    ;MOTOR2=1?
	GOTO	DERECHA	    ;MOTOR1 = 1 - MOTOR2 =0
	MOVLW	B'10011001' ;MOTOR1 = 1 - MOTOR2 = 1
SALIDA			    ;RB7 - RB0 
	MOVWF	PORTB
	;SERVO
	HOME
		BTFSS	PORTA,2
		GOTO	HOME_2
ZER		BSF		PORTB,6
		CALL	TIMEOF_500US
		BCF		PORTB,6
		CALL	TIMEOF_15MS
		CALL	TIMEOF_4MS
		CALL	TIMEOF_500US
HOME_2	BTFSS	PORTA,4
		GOTO	HOME
;NOVENTA GRADOS

NOV		BSF		PORTB,6
		CALL	TIMEOF_1MS
		CALL	TIMEOF_500US
		BCF		PORTB,6
		CALL	TIMEOF_16MS
		CALL	TIMEOF_2MS
		CALL	TIMEOF_500US
		


		;FIN SERVO
	GOTO	START
	END